### PR TITLE
Fixed Tipping Requests with additional Text

### PR DESCRIPTION
**Pull request by shubhiscoding**
This pull request was created by https://app.gib.work/i/PK_L2FNB/tipping-requests-with-additional-text-dont-work in an attempt to solve a bounty. Payment for the bounty is immediately sent to the contributor after merge.

### CODE REVIEW

**Comment by shubhiscoding** [comment]
this pr will fix #1

**Review by Redfox — CHANGES_REQUESTED** [review]
The build is failing

image

**Comment by shubhiscoding** [comment]
The TypeScript compiler is raising errors because it was unable to guarantee that certain variables won't be undefined. This happened when args.find() or args.indexOf() cannot find a match and return undefined, now it's fixed. and will fix #1 

> The build in failing
> 
> image

**Comment by anthonyliriano** [comment]
@gibworkbot tip 10 @shubhiscoding

**Comment by anthonyliriano** [comment]
@gibworkbot tip 10 @shubhiscoding

**Comment by anthonyliriano** [comment]
@gibworkbot tip 1 @shubhiscoding

**Comment by anthonyliriano** [comment]
@gibworkbot tip 10 @shubhiscoding

**Comment by Redfox** [comment]
@gibworkbot tip 10 @shubhiscoding

**Pull request closed without merging**
